language: ruby
cache: bundler
install: bundle install
script:
  - bundle exec rake book:build
after_success: |2
  (git describe | grep -v -E 'travis_[0-9]+-') || (
  # tag if no previous tag exists
  declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # Procedure to set up key pairs for remote tagging
  # $ travis login
  # $ travis setup releases --force
  # $ ssh-keygen -t rsa -b 4096 -C "<user.mail>" -f github_deploy_key -N ''
  # In GitHub admin page, select "Deploy keys", "Add deploy key"
  # Paste the content of github_deploy_key.pub
  # $ travis encrypt-file github_deploy_key
  # $ mkdir .travis && mv github_deploy_key.enc .travis
  # $ git add .travis/github_deploy_key.enc
  # $ rm -f github_deploy_key*
  # Edit travis.yml and change the decrypt command with correct env vars|
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -     v


  # Decrypt the file containing the private key
  openssl aes-256-cbc \
           -K $encrypted_89103fe9e218_key \
           -iv $encrypted_89103fe9e218_iv \
           -in ".travis/github_deploy_key.enc" \
           -out "$SSH_FILE" -d

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Enable SSH authentication

  chmod 600 "$SSH_FILE" \
           && printf "%s\n" \
           "Host github.com" \
           " IdentityFile $SSH_FILE" \
           "  LogLevel ERROR" >> ~/.ssh/config
  git config --global user.email "builds@travis-ci.com"
  git config --global user.name "Travis CI"
  export GIT_TAG=travis_$TRAVIS_BUILD_NUMBER
  git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  git remote add ssh git@github.com:${TRAVIS_REPO_SLUG}.git
  git push ssh master -q --tags )

deploy:
  provider: releases
  api_key:
    secure: VhtlP4trqy9laonJV+l/Z7+Zjo0+jc2bNuk/PQCJgAvr0i/utcW/LKUKus8D96mm6h79PrrvLE01yWqKmgMtfULPPSh2FZEnCC9QT2gma8ytI4zxQfD+hV+3KPt5GWj+ADT6Cvk5+Ute1THmaZnDLelmvZBRGzA1qX5KKqoouSMwR09dtC2bra4aSoG6qtbcC0/xt/EMFLDqq4jrpUoC2Tajyp55IhSiYv6dxhAhcogFxg1ezL7FURAFyslePo8fEICwGasX8bm4FVKK4aQIS/SxdvPkaHr1SqYMvdwD24IUypmQyX8PYd8in7L0g7Rg96S+31oH6F2GZjZyWAFug/vBZNqE+1qmt3TPt9DpVfkD8Rhj/4cMdjbP+lrMK4b6dogtRn0mzQOdRzBEntqwYG7KHP8JX41N9B2YkqlIX5GeO2/UgRIouqkeje+7iJWF1a7v++EaahUWKgPWwdeyMhLKs4yhGZGnnlfnqnirmN9tHiQTgRJhy45jkm0udhwNv6vO4QZPfAGXHlV4tnZUTW4mwOivT5gGcNfcBFNoHeRrZlpD9g9/ZsTuXdmgV3bz2BomSn8rCcXSH6jWzO8kDr/lT9CBonik9yblqUHv4jJyW27kaUR06HRJ4W07ZhzYGCokrHLxC51ZcNpCvy1kXKhajvLpaZbS8294OopQzIU=
  file:
    - "progit.epub"
    - "progit.pdf"
    - "progit-kf8.epub"
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
branches:
  only:
  - master
  - /^travis_[0-9]*$/

